services:
  - type: web
    name: your-django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key
