# Generated by Django 5.1.6 on 2025-02-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bus_registered_time_bus_registration_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='worker_permissions',
        ),
    ]
