# Generated by Django 5.1.6 on 2025-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_ticket_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
